export const CAREERS = [
    "Técnico profesional en Operaciones Turísticas Presencial",
    "Tecnólogo en Gestión de Turismo Sostenible Presencial",
    "Administrador Turístico y Hotelero Presencial",
    "Técnico profesional en Operaciones Turísticas Virtual",
    "Tecnólogo en Gestión de Turismo Sostenible Virtual",
    "Administrador Turístico y Hotelero Virtual",
    "Técnico Profesional en Procesos Aduaneros Virtual",
    "Tecnólogo en Gestión de Comercio Internacional Virtual",
    "Administrador de Negocios Internacionales Virtual",
    "Técnico Profesional en Operaciones Logísticas Virtual",
    "Tecnólogo en Gestión Logística Empresarial Virtual",
    "Profesional Universitario en Administración Virtual",
    "Técnico Profesional Operaciones Aduaneras y de Comercio Internacional Distancia",
    "Tecnólogo en Gestión de Marketing y Negocios Internacionales Distancia",
    "Administrador de Negocios Internacionales Distancia",
    "Técnico Profesional Operaciones Aduaneras y de Comercio Internacional Presencial",
    "Tecnólogo en Gestión de Marketing y Negocios Internacionales Presencial",
    "Administrador (a) de Negocios Internacionales Presencial",
    "Técnico Profesional en Procesos Contables Distancia",
    "Tecnólogo en Gestión Financiera Distancia",
    "Administrador Financiero Distancia",
    "Técnico Profesional en Procesos Contables Presencial",
    "Tecnólogo en Gestión Financiera Presencial",
    "Administrador Financiero Presencial",
    "Técnico Profesional en Soporte Informático",
    "Tecnólogo en Desarrollo de Software",
    "Profesional Universitario en Ingeniería de Software",
    "Técnico Profesional en Producción Gráfica",
    "Tecnólogo en Gestión de Contenidos Gráficos",
    "Diseñador Gráfico",
    "Técnico en Procesos Administrativos de Diseño de Modas",
    "Tecnólogo en Gestión de Diseño de Modas",
    "Diseñador y Administrador de Negocios de la Moda",
    "Especialista Gestión Pública",
    "Especialista en Analítica de Datos para los Negocios",
    "Especialista Marketing Digital Estrategico",
    "Tecnólogo Marketing y Negocios Internacionales",
    "Tecnólogo en Gestión de Negocios Internacionales Ocaña",
    "Administrador de Negocios Internacionales Ocaña",
    "Tecnólogo en Producción Gráfica Ocaña",
    "Profesional en Diseño Gráfico Ocaña",
    "Tecnólogo en Gestión Financiera Ocaña",
    "Profesional en Administración Financiera Ocaña"
];
